name: build
on:
  push:
    paths:
      - 'common/src/main/java/**'
      - 'fabric/src/main/java/**'
      - 'neoforge/src/main/java/**'
      - '**/gradle.properties'
      - '**/settings.gradle'
      - '**/build.gradle'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Rename build files to include SHA
        run: |
         SHA=$(git rev-parse --short HEAD)
         FILENAME=$(ls ./neoforge/build/libs/*.jar | grep -v "sources" | head -n 1)
         FILENAME2=$(ls ./fabric/build/libs/*.jar | grep -v "sources" | head -n 1)
         mv -- "$FILENAME" "${FILENAME%.jar}-GIT-$SHA.jar"
         mv -- "$FILENAME2" "${FILENAME2%.jar}-GIT-$SHA.jar"
        
      - name: Upload Neoforge JAR to artifacts
        uses: actions/upload-artifact@v7
        with:
          archive: false
          retention-days: 90
          path: ./neoforge/build/libs/*-GIT-*.jar

      - name: Upload Fabric JAR to artifacts
        uses: actions/upload-artifact@v7
        with:
          archive: false
          retention-days: 90
          path: ./fabric/build/libs/*-GIT-*.jar
